name: shake_gesture_platform_interface
description: A common platform interface for the shake_gesture plugin.
version: 0.1.1
homepage: https://github.com/tpucci/shake_gesture
repository: https://github.com/tpucci/shake_gesture

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0
